feat(MWPW-152287): Adds support for Events custom banners
adobecom/caas pull request #158
Opened 2024-06-12 11:34 UTC by cmiqueo

Adds Adds support for Events custom banners. 

**IMPORTANT**: For the new In-Person treatment the cards MUST be tagged as 
`events/session-format/in-person`

- Live Online: **LIVE** _(default - current behavior)_
- Live In-Person: **LIVE NOW**  _(new - custom behavior)_

- OnDemand Online: **ON DEMAND** _(default - current behavior)_
- OnDemand In-Person: no banner  _(new - custom behavior)_

2024-06-21 17:31 UTC, sheridansunier approved these changes

2024-06-21 17:41 UTC, sheridansunier requested changes
the e2e tests are failing - plz fix :P

2024-06-26 17:10 UTC, cmiqueo commented
> the e2e tests are failing - plz fix :P

Fixed!

2024-06-26 17:33 UTC, sheridansunier approved these changes

2024-06-26 17:45 UTC, merged