MWPW-159159(fix): Updates overlay links aria-label value
adobecom/caas pull request #180
Opened 2024-09-27 18:18 UTC by cmiqueo

Description:
This PR replaces the aria-label value for the overlay links so that instead of the link URL string it will display the card title.

Resolves:  
https://jira.corp.adobe.com/browse/MWPW-159159

Before:
```
<a href="https://www.adobe.com/creativecloud/photography/discover/pet-photography.html" 
   target="_self" 
   rel="noopener noreferrer" 
   aria-label="https://www.adobe.com/creativecloud/photography/discover/pet-photography.html" 
   tabindex="0" 
   class="consonant-LinkBlocker"
></a>
```

After:
```
<a href="https://www.adobe.com/creativecloud/photography/discover/pet-photography.html" 
   target="_self" 
   rel="noopener noreferrer" 
   aria-label="Learn the best dog & cat photography tips" 
   tabindex="0" 
   class="consonant-LinkBlocker"
></a>
```

2024-09-27 20:48 UTC, sanrai commented
format should be `fix(MWPW-159159): Updates overlay links aria-label` for PR title and git commit message. 

Please `git commit amend and fix`

2024-09-27 20:54 UTC, sanrai requested changes
Update git comm

2024-09-30 16:52 UTC, cmiqueo commented
> format should be `fix(MWPW-159159): Updates overlay links aria-label` for PR title and git commit message.
> 
> Please `git commit amend` to fix

Good catch! :)

2024-09-30 17:04 UTC, sanrai approved these changes

2024-09-30 20:34 UTC, sheridansunier approved these changes

2024-09-30 21:33 UTC, merged